name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
       # npm cache files are stored in `~/.npm` on ubuntu-latest
        path: ~/.npm
        key: ${{ runner.os }}-build-cache-node-modules
        restore-keys: |
          ${{ runner.os }}-build-cache-node-modules

    - name : Install Dependencies for npm
      run: |
        working-directory: ./src/main/my-app
        npm ci
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.3.2'
        arguments: build
    - name: Build NPM
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.3.2'
        arguments: npmBuild